version: "3.1"
  
services:
  # More info at https://github.com/wodby/mariadb
  mariadb:
    image: wodby/mariadb:${MARIADB_TAG-10.1}
    stop_grace_period: 30s
    environment:
      MYSQL_DATABASE: bfv
      MYSQL_USER: bfv
      MYSQL_PASSWORD: bfv
      MYSQL_ROOT_PASSWORD: changemeplease
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - '3106:3306'

volumes:
  mariadb:

